Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import re
... import sys
... 
... 
... def main():
...     print(parse(input("HTML: ")))
... 
... 
... def parse(s):
...     if result := re.search(r'.+src="https?://(?:www\.)?youtube\.com/embed/([a-z0-9A-Z]+)"',s):
...         return "https://youtu.be/" + result.group(1)
... 
... 
... if __name__ == "__main__":
